# Gera::ExportToBestchangeWorker:
#  cron: '*/3 * * * * *'
#  class: Gera::ExportToBestchangeWorker
#  queue: critical

### Cleaners
#
# Чистка во время тех перерыва 00:30-01:00
# CurrencyRateHistoryIntervalCleanerWorker:
#   cron: '40 0 * * *'
#   class: CurrencyRateHistoryIntervalCleanerWorker
#   queue: default

# DirectionRateHistoryIntervalCleanerWorker:
#   cron: '50 0 * * *'
#   class: DirectionRateHistoryIntervalCleanerWorker
#   queue: default

# VacuumWorker:
#   cron: '34 5 * * *'
#   class: VacuumWorker
#   queue: default

###
#### Gera
#
# Обновляем раз в 15 минут просто на всякий случай
#

# Gera::PurgeCurrencyRatesWorker:
#   cron: '27 2 * * *'
#   class: Gera::PurgeCurrencyRatesWorker
#   queue: purgers

# Gera::PurgeDirectionRatesWorker:
#   cron: '27 3 * * *'
#   class: Gera::PurgeDirectionRatesWorker
#   queue: purgers

# Gera::PurgeExternalRatesWorker:
#   cron: '27 4 * * *'
#   class: Gera::PurgeExternalRatesWorker
#   queue: purgers

# Gera::CreateHistoryIntervalsWorker:
#   cron: '*/17 * * * *'
#   class: Gera::CreateHistoryIntervalsWorker
#   queue: default
